# Module 8: Interoperation and IO

In [ ]:
import polars as pl

In [ ]:
df = pl.DataFrame(
    {
        "first_name": ["dan", "stan", "ron", "dawn"],
        "last_name": ["flanson", "dfs", "thoman", "ronin"]
    }
)
df

In [ ]:
df = pl.from_dicts(
    [
        {"first_name": "dan", "second_name": "flansons"},
        {"first_name": "van", "second_name": "sldfj"},
        {"first_name": "man", "second_name": "stuary"},
        {"first_name": "rom", "second_name": "parker"},
    ]
)
df

In [ ]:
df = pl.from_records(
    [
        ["dan", "flanson"],
        ["van", "robert"],
        ["gan", "xavier"],
        ["xan", "robert"],
    ],
    schema=["first_name", "last_name"],
)
df

## Interoperating using Series

In [ ]:
df.to_dict()

In [ ]:
df_from_series = pl.DataFrame(
    [
        pl.Series(name="first_name", values=["dan", "man", "van", "john"]),
        pl.Series(name="last_name", values=["dawn", "manning", "vanning", "johning"])
    ]
)

In [ ]:
df_from_series

In [ ]:
df_from_series.to_series(1)

## Interoperation with Pandas Dataframe

In [ ]:
df = pl.DataFrame(
    {
        "first_name": ["dan", "stan", "ron", "dawn"],
        "last_name": ["flanson", "dfs", "thoman", "ronin"]
    }
)
pandas_df = df.to_pandas()
print(type(pandas_df))

## Interoperation with Numpy Arrays

In [ ]:
numpy_obj = df.to_numpy()

In [ ]:
pl.from_numpy(numpy_obj, schema=["first_name", "last_name"])

## Dataframe IO

In [ ]:
df.write_excel("./../data/toy_df.xlsx")

In [ ]:
pl.read_excel("./../data/toy_df.xlsx")

In [ ]:
yellow_rides_column_rename_mapping = {
    "VendorID": "vendor_id",
    "RatecodeID": "rate_code_id",
    "PULocationID": "pickup_location_id",
    "DOLocationID": "dropoff_location_id",
    "Airport_fee": "airport_fee",
}

march_yellow_rides_df = (
    pl.read_parquet("./../data/yellow_tripdata_2024-03.parquet").rename(
        yellow_rides_column_rename_mapping
    ).with_columns(
        pl.col("tpep_pickup_datetime").dt.date().alias("tpep_pickup_date")
    )
)

In [ ]:
march_yellow_rides_df

In [ ]:
march_yellow_rides_df.write_parquet(
    "./../data/parquet_partitions/partitioned_march_rides/",
    use_pyarrow=True,
    pyarrow_options={"partition_cols": ["tpep_pickup_date"]}
)

In [ ]:
loaded_df_partition = pl.read_parquet(
    "./../data/parquet_partitions/partitioned_march_rides/",
    use_pyarrow=True,
)
loaded_df_partition

In [ ]:
loaded_df_partition = pl.read_parquet(
    "./../data/parquet_partitions/partitioned_march_rides/tpep_pickup_date=2024-03-06/",
    use_pyarrow=True,
)
loaded_df_partition

In [23]:
data = [
    ["bonnie", "ronnie", "donny", "johnny", "scrawny"],
    list(range(5)),
    list(range(4, 9)),
]
pl.from_records(data, orient="col")

shape: (5, 3)
┌──────────┬──────────┬──────────┐
│ column_0 ┆ column_1 ┆ column_2 │
│ ---      ┆ ---      ┆ ---      │
│ str      ┆ i64      ┆ i64      │
╞══════════╪══════════╪══════════╡
│ bonnie   ┆ 0        ┆ 4        │
│ ronnie   ┆ 1        ┆ 5        │
│ donny    ┆ 2        ┆ 6        │
│ johnny   ┆ 3        ┆ 7        │
│ scrawny  ┆ 4        ┆ 8        │
└──────────┴──────────┴──────────┘

In [ ]:
save_path = "temp_file.njson"
df = pl.DataFrame([
    pl.Series(name="a", values=500 * ["derek", "carole"]),
    pl.Series(name="b", values=list(range(1000))),
    pl.Series(name="c", values=[i % 4 for i in list(range(1000))], dtype=pl.UInt8),
])

In [25]:
df

shape: (1_000, 3)
┌────────┬─────┬─────┐
│ a      ┆ b   ┆ c   │
│ ---    ┆ --- ┆ --- │
│ str    ┆ i64 ┆ u8  │
╞════════╪═════╪═════╡
│ derek  ┆ 0   ┆ 0   │
│ carole ┆ 1   ┆ 1   │
│ derek  ┆ 2   ┆ 2   │
│ carole ┆ 3   ┆ 3   │
│ derek  ┆ 4   ┆ 0   │
│ …      ┆ …   ┆ …   │
│ carole ┆ 995 ┆ 3   │
│ derek  ┆ 996 ┆ 0   │
│ carole ┆ 997 ┆ 1   │
│ derek  ┆ 998 ┆ 2   │
│ carole ┆ 999 ┆ 3   │
└────────┴─────┴─────┘

In [26]:
df.write_ndjson(save_path)

In [27]:
df = pl.read_ndjson(save_path)

In [28]:
df

shape: (1_000, 3)
┌────────┬─────┬─────┐
│ a      ┆ b   ┆ c   │
│ ---    ┆ --- ┆ --- │
│ str    ┆ i64 ┆ i64 │
╞════════╪═════╪═════╡
│ derek  ┆ 0   ┆ 0   │
│ carole ┆ 1   ┆ 1   │
│ derek  ┆ 2   ┆ 2   │
│ carole ┆ 3   ┆ 3   │
│ derek  ┆ 4   ┆ 0   │
│ …      ┆ …   ┆ …   │
│ carole ┆ 995 ┆ 3   │
│ derek  ┆ 996 ┆ 0   │
│ carole ┆ 997 ┆ 1   │
│ derek  ┆ 998 ┆ 2   │
│ carole ┆ 999 ┆ 3   │
└────────┴─────┴─────┘

In [31]:
data = [
    ["bonnie", "ronnie", "donny", "johnny", "scrawny"],
    list(range(5)),
    list(range(4, 9)),
]
pl.from_records(data, orient="row")

shape: (3, 5)
┌──────────┬──────────┬──────────┬──────────┬──────────┐
│ column_0 ┆ column_1 ┆ column_2 ┆ column_3 ┆ column_4 │
│ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str      ┆ str      ┆ str      ┆ str      ┆ str      │
╞══════════╪══════════╪══════════╪══════════╪══════════╡
│ bonnie   ┆ ronnie   ┆ donny    ┆ johnny   ┆ scrawny  │
│ 0        ┆ 1        ┆ 2        ┆ 3        ┆ 4        │
│ 4        ┆ 5        ┆ 6        ┆ 7        ┆ 8        │
└──────────┴──────────┴──────────┴──────────┴──────────┘

In [32]:
save_path = "temp_file.parquet"
df = pl.DataFrame([
    pl.Series(name="a", values=500 * ["derek", "carole"]),
    pl.Series(name="b", values=list(range(1000))),
    pl.Series(name="c", values=[i % 4 for i in list(range(1000))], dtype=pl.UInt8),
])
df

shape: (1_000, 3)
┌────────┬─────┬─────┐
│ a      ┆ b   ┆ c   │
│ ---    ┆ --- ┆ --- │
│ str    ┆ i64 ┆ u8  │
╞════════╪═════╪═════╡
│ derek  ┆ 0   ┆ 0   │
│ carole ┆ 1   ┆ 1   │
│ derek  ┆ 2   ┆ 2   │
│ carole ┆ 3   ┆ 3   │
│ derek  ┆ 4   ┆ 0   │
│ …      ┆ …   ┆ …   │
│ carole ┆ 995 ┆ 3   │
│ derek  ┆ 996 ┆ 0   │
│ carole ┆ 997 ┆ 1   │
│ derek  ┆ 998 ┆ 2   │
│ carole ┆ 999 ┆ 3   │
└────────┴─────┴─────┘

In [33]:
df.write_parquet(save_path)

In [34]:
pl.read_parquet(save_path)

shape: (1_000, 3)
┌────────┬─────┬─────┐
│ a      ┆ b   ┆ c   │
│ ---    ┆ --- ┆ --- │
│ str    ┆ i64 ┆ u8  │
╞════════╪═════╪═════╡
│ derek  ┆ 0   ┆ 0   │
│ carole ┆ 1   ┆ 1   │
│ derek  ┆ 2   ┆ 2   │
│ carole ┆ 3   ┆ 3   │
│ derek  ┆ 4   ┆ 0   │
│ …      ┆ …   ┆ …   │
│ carole ┆ 995 ┆ 3   │
│ derek  ┆ 996 ┆ 0   │
│ carole ┆ 997 ┆ 1   │
│ derek  ┆ 998 ┆ 2   │
│ carole ┆ 999 ┆ 3   │
└────────┴─────┴─────┘

In [35]:
save_path = "temp_file.csv"
df = pl.DataFrame([
    pl.Series(name="a", values=500 * ["derek", "carole"]),
    pl.Series(name="b", values=list(range(1000))),
    pl.Series(name="c", values=[i % 4 for i in list(range(1000))], dtype=pl.UInt8),
])
df

shape: (1_000, 3)
┌────────┬─────┬─────┐
│ a      ┆ b   ┆ c   │
│ ---    ┆ --- ┆ --- │
│ str    ┆ i64 ┆ u8  │
╞════════╪═════╪═════╡
│ derek  ┆ 0   ┆ 0   │
│ carole ┆ 1   ┆ 1   │
│ derek  ┆ 2   ┆ 2   │
│ carole ┆ 3   ┆ 3   │
│ derek  ┆ 4   ┆ 0   │
│ …      ┆ …   ┆ …   │
│ carole ┆ 995 ┆ 3   │
│ derek  ┆ 996 ┆ 0   │
│ carole ┆ 997 ┆ 1   │
│ derek  ┆ 998 ┆ 2   │
│ carole ┆ 999 ┆ 3   │
└────────┴─────┴─────┘

In [36]:
df.write_csv(save_path)

In [37]:
pl.read_csv(save_path)

shape: (1_000, 3)
┌────────┬─────┬─────┐
│ a      ┆ b   ┆ c   │
│ ---    ┆ --- ┆ --- │
│ str    ┆ i64 ┆ i64 │
╞════════╪═════╪═════╡
│ derek  ┆ 0   ┆ 0   │
│ carole ┆ 1   ┆ 1   │
│ derek  ┆ 2   ┆ 2   │
│ carole ┆ 3   ┆ 3   │
│ derek  ┆ 4   ┆ 0   │
│ …      ┆ …   ┆ …   │
│ carole ┆ 995 ┆ 3   │
│ derek  ┆ 996 ┆ 0   │
│ carole ┆ 997 ┆ 1   │
│ derek  ┆ 998 ┆ 2   │
│ carole ┆ 999 ┆ 3   │
└────────┴─────┴─────┘