In [2]:
import polars as pl

In [3]:
column_rename_mapping = {
    "VendorID": "vendor_id",
    "RatecodeID": "rate_code_id",
    "PULocationID": "pickup_location_id",
    "DOLocationID": "dropoff_location_id",
    "Airport_fee": "airport_fee",
}
march_yellow_df = pl.read_parquet("./../data/yellow_tripdata_2024-03.parquet").rename(
    column_rename_mapping
)

## Joining Dataframes

In [4]:
location_id_summary_df = march_yellow_df.group_by("pickup_location_id").agg(
    pl.len().alias("count_trips"),
    pl.col("trip_distance").min().name.suffix("_min"),
    pl.col("trip_distance").mean().name.suffix("_mean"),
    pl.col("trip_distance").max().name.suffix("_max"),
)
location_id_summary_df.head()

shape: (5, 5)
┌────────────────────┬─────────────┬───────────────────┬────────────────────┬───────────────────┐
│ pickup_location_id ┆ count_trips ┆ trip_distance_min ┆ trip_distance_mean ┆ trip_distance_max │
│ ---                ┆ ---         ┆ ---               ┆ ---                ┆ ---               │
│ i32                ┆ u32         ┆ f64               ┆ f64                ┆ f64               │
╞════════════════════╪═════════════╪═══════════════════╪════════════════════╪═══════════════════╡
│ 140                ┆ 70384       ┆ 0.0               ┆ 3.992814           ┆ 66838.02          │
│ 200                ┆ 138         ┆ 0.0               ┆ 8.488551           ┆ 29.6              │
│ 150                ┆ 107         ┆ 0.0               ┆ 8.272804           ┆ 72.54             │
│ 84                 ┆ 1           ┆ 20.11             ┆ 20.11              ┆ 20.11             │
│ 120                ┆ 29          ┆ 0.0               ┆ 4.934828           ┆ 23.37             │
└────────────────────┴─────────────┴───────────────────┴────────────────────┴───────────────────┘

In [5]:
column_rename_mapping_zones = {
    "LocationID": "location_id",
    "Borough": "borough",
    "Zone": "zone",
}
zones_df = pl.read_parquet("./../data/taxi_zone_lookup.parquet").rename(
    column_rename_mapping_zones
)
zones_df.head()

shape: (5, 4)
┌─────────────┬───────────────┬─────────────────────────┬──────────────┐
│ location_id ┆ borough       ┆ zone                    ┆ service_zone │
│ ---         ┆ ---           ┆ ---                     ┆ ---          │
│ i32         ┆ str           ┆ str                     ┆ str          │
╞═════════════╪═══════════════╪═════════════════════════╪══════════════╡
│ 1           ┆ EWR           ┆ Newark Airport          ┆ EWR          │
│ 2           ┆ Queens        ┆ Jamaica Bay             ┆ Boro Zone    │
│ 3           ┆ Bronx         ┆ Allerton/Pelham Gardens ┆ Boro Zone    │
│ 4           ┆ Manhattan     ┆ Alphabet City           ┆ Yellow Zone  │
│ 5           ┆ Staten Island ┆ Arden Heights           ┆ Boro Zone    │
└─────────────┴───────────────┴─────────────────────────┴──────────────┘

In [6]:
location_id_summary_df.join(
    zones_df, left_on="pickup_location_id", right_on="location_id"
)

shape: (259, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ pickup_loc ┆ count_trip ┆ trip_dista ┆ trip_dist ┆ trip_dist ┆ borough   ┆ zone      ┆ service_z │
│ ation_id   ┆ s          ┆ nce_min    ┆ ance_mean ┆ ance_max  ┆ ---       ┆ ---       ┆ one       │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ str       ┆ str       ┆ ---       │
│ i32        ┆ u32        ┆ f64        ┆ f64       ┆ f64       ┆           ┆           ┆ str       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1          ┆ 372        ┆ 0.0        ┆ 1.34578   ┆ 35.75     ┆ EWR       ┆ Newark    ┆ EWR       │
│            ┆            ┆            ┆           ┆           ┆           ┆ Airport   ┆           │
│ 2          ┆ 8          ┆ 0.0        ┆ 11.98     ┆ 20.23     ┆ Queens    ┆ Jamaica   ┆ Boro Zone │
│            ┆            ┆            ┆           ┆           ┆           ┆ Bay       ┆           │
│ 3          ┆ 151        ┆ 0.0        ┆ 7.159073  ┆ 35.1      ┆ Bronx     ┆ Allerton/ ┆ Boro Zone │
│            ┆            ┆            ┆           ┆           ┆           ┆ Pelham    ┆           │
│            ┆            ┆            ┆           ┆           ┆           ┆ Gardens   ┆           │
│ 4          ┆ 7586       ┆ 0.0        ┆ 2.742518  ┆ 37.6      ┆ Manhattan ┆ Alphabet  ┆ Yellow    │
│            ┆            ┆            ┆           ┆           ┆           ┆ City      ┆ Zone      │
│ 5          ┆ 1          ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ Staten    ┆ Arden     ┆ Boro Zone │
│            ┆            ┆            ┆           ┆           ┆ Island    ┆ Heights   ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ 261        ┆ 18849      ┆ 0.0        ┆ 4.178514  ┆ 49.06     ┆ Manhattan ┆ World     ┆ Yellow    │
│            ┆            ┆            ┆           ┆           ┆           ┆ Trade     ┆ Zone      │
│            ┆            ┆            ┆           ┆           ┆           ┆ Center    ┆           │
│ 262        ┆ 48890      ┆ 0.0        ┆ 8.245881  ┆ 176329.23 ┆ Manhattan ┆ Yorkville ┆ Yellow    │
│            ┆            ┆            ┆           ┆           ┆           ┆ East      ┆ Zone      │
│ 263        ┆ 68956      ┆ 0.0        ┆ 8.095303  ┆ 176836.3  ┆ Manhattan ┆ Yorkville ┆ Yellow    │
│            ┆            ┆            ┆           ┆           ┆           ┆ West      ┆ Zone      │
│ 264        ┆ 11567      ┆ 0.0        ┆ 3.261509  ┆ 56.2      ┆ Unknown   ┆ N/A       ┆ N/A       │
│ 265        ┆ 2081       ┆ 0.0        ┆ 8.877866  ┆ 8917.7    ┆ N/A       ┆ Outside   ┆ N/A       │
│            ┆            ┆            ┆           ┆           ┆           ┆ of NYC    ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [7]:
march_yellow_df.select(
    "tpep_pickup_datetime",
    "pickup_location_id",
    "dropoff_location_id",
    "trip_distance",
    "total_amount",
).join(zones_df, left_on="pickup_location_id", right_on="location_id")

shape: (3_582_628, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ tpep_picku ┆ pickup_loc ┆ dropoff_lo ┆ trip_dist ┆ total_amo ┆ borough   ┆ zone      ┆ service_z │
│ p_datetime ┆ ation_id   ┆ cation_id  ┆ ance      ┆ unt       ┆ ---       ┆ ---       ┆ one       │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ str       ┆ str       ┆ ---       │
│ datetime[n ┆ i32        ┆ i32        ┆ f64       ┆ f64       ┆           ┆           ┆ str       │
│ s]         ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2024-03-01 ┆ 142        ┆ 239        ┆ 1.3       ┆ 16.3      ┆ Manhattan ┆ Lincoln   ┆ Yellow    │
│ 00:18:51   ┆            ┆            ┆           ┆           ┆           ┆ Square    ┆ Zone      │
│            ┆            ┆            ┆           ┆           ┆           ┆ East      ┆           │
│ 2024-03-01 ┆ 238        ┆ 24         ┆ 1.1       ┆ 15.2      ┆ Manhattan ┆ Upper     ┆ Yellow    │
│ 00:26:00   ┆            ┆            ┆           ┆           ┆           ┆ West Side ┆ Zone      │
│            ┆            ┆            ┆           ┆           ┆           ┆ North     ┆           │
│ 2024-03-01 ┆ 263        ┆ 75         ┆ 0.86      ┆ 10.4      ┆ Manhattan ┆ Yorkville ┆ Yellow    │
│ 00:09:22   ┆            ┆            ┆           ┆           ┆           ┆ West      ┆ Zone      │
│ 2024-03-01 ┆ 164        ┆ 162        ┆ 0.82      ┆ 14.19     ┆ Manhattan ┆ Midtown   ┆ Yellow    │
│ 00:33:45   ┆            ┆            ┆           ┆           ┆           ┆ South     ┆ Zone      │
│ 2024-03-01 ┆ 263        ┆ 7          ┆ 4.9       ┆ 30.4      ┆ Manhattan ┆ Yorkville ┆ Yellow    │
│ 00:05:43   ┆            ┆            ┆           ┆           ┆           ┆ West      ┆ Zone      │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2024-03-31 ┆ 130        ┆ 218        ┆ 4.27      ┆ 15.77     ┆ Queens    ┆ Jamaica   ┆ Boro Zone │
│ 23:16:45   ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ 2024-03-31 ┆ 79         ┆ 100        ┆ 0.0       ┆ 24.8      ┆ Manhattan ┆ East      ┆ Yellow    │
│ 23:29:28   ┆            ┆            ┆           ┆           ┆           ┆ Village   ┆ Zone      │
│ 2024-03-31 ┆ 63         ┆ 181        ┆ 6.44      ┆ 31.5      ┆ Brooklyn  ┆ Cypress   ┆ Boro Zone │
│ 23:15:00   ┆            ┆            ┆           ┆           ┆           ┆ Hills     ┆           │
│ 2024-03-31 ┆ 161        ┆ 148        ┆ 3.88      ┆ 31.58     ┆ Manhattan ┆ Midtown   ┆ Yellow    │
│ 23:27:53   ┆            ┆            ┆           ┆           ┆           ┆ Center    ┆ Zone      │
│ 2024-03-31 ┆ 95         ┆ 7          ┆ 7.39      ┆ 32.97     ┆ Queens    ┆ Forest    ┆ Boro Zone │
│ 23:10:50   ┆            ┆            ┆           ┆           ┆           ┆ Hills     ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [8]:
zone_columns = [
    "borough",
    "zone",
    "service_zone",
]

march_yellow_df.select(
    "tpep_pickup_datetime",
    "pickup_location_id",
    "dropoff_location_id",
    "trip_distance",
    "total_amount",
).join(zones_df, left_on="pickup_location_id", right_on="location_id").with_columns(
    pl.col(zone_columns).name.prefix("pickup_")
).drop(zone_columns)

shape: (3_582_628, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ tpep_picku ┆ pickup_loc ┆ dropoff_lo ┆ trip_dist ┆ total_amo ┆ pickup_bo ┆ pickup_zo ┆ pickup_se │
│ p_datetime ┆ ation_id   ┆ cation_id  ┆ ance      ┆ unt       ┆ rough     ┆ ne        ┆ rvice_zon │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ e         │
│ datetime[n ┆ i32        ┆ i32        ┆ f64       ┆ f64       ┆ str       ┆ str       ┆ ---       │
│ s]         ┆            ┆            ┆           ┆           ┆           ┆           ┆ str       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2024-03-01 ┆ 142        ┆ 239        ┆ 1.3       ┆ 16.3      ┆ Manhattan ┆ Lincoln   ┆ Yellow    │
│ 00:18:51   ┆            ┆            ┆           ┆           ┆           ┆ Square    ┆ Zone      │
│            ┆            ┆            ┆           ┆           ┆           ┆ East      ┆           │
│ 2024-03-01 ┆ 238        ┆ 24         ┆ 1.1       ┆ 15.2      ┆ Manhattan ┆ Upper     ┆ Yellow    │
│ 00:26:00   ┆            ┆            ┆           ┆           ┆           ┆ West Side ┆ Zone      │
│            ┆            ┆            ┆           ┆           ┆           ┆ North     ┆           │
│ 2024-03-01 ┆ 263        ┆ 75         ┆ 0.86      ┆ 10.4      ┆ Manhattan ┆ Yorkville ┆ Yellow    │
│ 00:09:22   ┆            ┆            ┆           ┆           ┆           ┆ West      ┆ Zone      │
│ 2024-03-01 ┆ 164        ┆ 162        ┆ 0.82      ┆ 14.19     ┆ Manhattan ┆ Midtown   ┆ Yellow    │
│ 00:33:45   ┆            ┆            ┆           ┆           ┆           ┆ South     ┆ Zone      │
│ 2024-03-01 ┆ 263        ┆ 7          ┆ 4.9       ┆ 30.4      ┆ Manhattan ┆ Yorkville ┆ Yellow    │
│ 00:05:43   ┆            ┆            ┆           ┆           ┆           ┆ West      ┆ Zone      │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2024-03-31 ┆ 130        ┆ 218        ┆ 4.27      ┆ 15.77     ┆ Queens    ┆ Jamaica   ┆ Boro Zone │
│ 23:16:45   ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ 2024-03-31 ┆ 79         ┆ 100        ┆ 0.0       ┆ 24.8      ┆ Manhattan ┆ East      ┆ Yellow    │
│ 23:29:28   ┆            ┆            ┆           ┆           ┆           ┆ Village   ┆ Zone      │
│ 2024-03-31 ┆ 63         ┆ 181        ┆ 6.44      ┆ 31.5      ┆ Brooklyn  ┆ Cypress   ┆ Boro Zone │
│ 23:15:00   ┆            ┆            ┆           ┆           ┆           ┆ Hills     ┆           │
│ 2024-03-31 ┆ 161        ┆ 148        ┆ 3.88      ┆ 31.58     ┆ Manhattan ┆ Midtown   ┆ Yellow    │
│ 23:27:53   ┆            ┆            ┆           ┆           ┆           ┆ Center    ┆ Zone      │
│ 2024-03-31 ┆ 95         ┆ 7          ┆ 7.39      ┆ 32.97     ┆ Queens    ┆ Forest    ┆ Boro Zone │
│ 23:10:50   ┆            ┆            ┆           ┆           ┆           ┆ Hills     ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

## Concat

In [9]:
toy_1_df = pl.DataFrame({
    "a": [1, 2, 4],
    "b": [5, 7, 8],
})
toy_2_df = pl.DataFrame({
    "a": [10, 20, 50, 90],
    "b": [50, 3, 99, 3],
    "c": [4, 6, 10, 12]
})
print(toy_1_df)
print(toy_2_df)
result = (
    pl.concat(
        [toy_1_df,
        toy_2_df],
        how="diagonal"
    )
)
print(result)

shape: (3, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 5   │
│ 2   ┆ 7   │
│ 4   ┆ 8   │
└─────┴─────┘
shape: (4, 3)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 10  ┆ 50  ┆ 4   │
│ 20  ┆ 3   ┆ 6   │
│ 50  ┆ 99  ┆ 10  │
│ 90  ┆ 3   ┆ 12  │
└─────┴─────┴─────┘
shape: (7, 3)
┌─────┬─────┬──────┐
│ a   ┆ b   ┆ c    │
│ --- ┆ --- ┆ ---  │
│ i64 ┆ i64 ┆ i64  │
╞═════╪═════╪══════╡
│ 1   ┆ 5   ┆ null │
│ 2   ┆ 7   ┆ null │
│ 4   ┆ 8   ┆ null │
│ 10  ┆ 50  ┆ 4    │
│ 20  ┆ 3   ┆ 6    │
│ 50  ┆ 99  ┆ 10   │
│ 90  ┆ 3   ┆ 12   │
└─────┴─────┴──────┘

In [10]:
march_yellow_df.join(
    zones_df,
    left_on="pickup_location_id",
    right_on="location_id",
).rename(
    {
        "borough": "pickup_borough",
        "zone": "pickup_zone",
    }
).join(
    zones_df,
    left_on="dropoff_location_id",
    right_on="location_id",
).rename(
    {
        "borough": "dropoff_borough",
        "zone": "dropoff_zone",
    }
).group_by(
    ["pickup_zone", "dropoff_zone"]
).agg(
pl.col("passenger_count").mean()
).filter(
    pl.col("pickup_zone").eq("Midtown Center").and_(
        pl.col("dropoff_zone").eq("Upper East Side North")
    )
)

shape: (1, 3)
┌────────────────┬───────────────────────┬─────────────────┐
│ pickup_zone    ┆ dropoff_zone          ┆ passenger_count │
│ ---            ┆ ---                   ┆ ---             │
│ str            ┆ str                   ┆ f64             │
╞════════════════╪═══════════════════════╪═════════════════╡
│ Midtown Center ┆ Upper East Side North ┆ 1.277752        │
└────────────────┴───────────────────────┴─────────────────┘

march_yellow_df

In [11]:
march_yellow_df

shape: (3_582_628, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ vendor_id ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_ │
│ ---       ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ fee      │
│ i32       ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---      │
│           ┆ ---       ┆ ---       ┆ i64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ f64      │
│           ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ f64       ┆          │
│           ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 2024-03-0 ┆ 2024-03-0 ┆ 0         ┆ … ┆ 1.0       ┆ 16.3      ┆ 2.5       ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 00:18:51  ┆ 00:23:45  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1         ┆ 2024-03-0 ┆ 2024-03-0 ┆ 0         ┆ … ┆ 1.0       ┆ 15.2      ┆ 2.5       ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 00:26:00  ┆ 00:29:06  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2024-03-0 ┆ 2024-03-0 ┆ 1         ┆ … ┆ 1.0       ┆ 10.4      ┆ 0.0       ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 00:09:22  ┆ 00:15:24  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2024-03-0 ┆ 2024-03-0 ┆ 1         ┆ … ┆ 1.0       ┆ 14.19     ┆ 2.5       ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 00:33:45  ┆ 00:39:34  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1         ┆ 2024-03-0 ┆ 2024-03-0 ┆ 0         ┆ … ┆ 1.0       ┆ 30.4      ┆ 2.5       ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 00:05:43  ┆ 00:26:22  ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2         ┆ 2024-03-3 ┆ 2024-03-3 ┆ null      ┆ … ┆ 1.0       ┆ 15.77     ┆ null      ┆ null     │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 23:16:45  ┆ 23:29:20  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1         ┆ 2024-03-3 ┆ 2024-03-3 ┆ null      ┆ … ┆ 1.0       ┆ 24.8      ┆ null      ┆ null     │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 23:29:28  ┆ 23:43:47  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2024-03-3 ┆ 2024-03-3 ┆ null      ┆ … ┆ 1.0       ┆ 31.5      ┆ null      ┆ null     │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 23:15:00  ┆ 23:47:29  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2024-03-3 ┆ 2024-03-3 ┆ null      ┆ … ┆ 1.0       ┆ 31.58     ┆ null      ┆ null     │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 23:27:53  ┆ 23:45:44  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2024-03-3 ┆ 2024-03-3 ┆ null      ┆ … ┆ 1.0       ┆ 32.97     ┆ null      ┆ null     │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 23:10:50  ┆ 23:31:59  ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘